### ISSUE TITLE
Error setting up entry Securitas Sverige AB:***@me.com for alarmdotcom

### ISSUE THREAD

**Issue by Brkie** [uvjustin/alarmdotcom#95] opened 2022-03-05 10:15 UTC
Hi,

i updated yesterday to 2022.3.1 and also to the latest version in HACS of alarmdotcom. The migration did not work, i deleted all code in in config file and created a new integration thru integration page. All sensors showed up, I placed them in right rooms and so long so good.

Today when I restarted my HA - there is a new error and i cant figure it out. Here is the error:

Logger: homeassistant.config_entries
Source: custom_components/alarmdotcom/controller.py:109
Integration: Alarm.com ([documentation](https://www.github.com/uvjustin/alarmdotcom), [issues](https://www.github.com/uvjustin/alarmdotcom/issues))
First occurred: 10:59:38 (1 occurrences)
Last logged: 10:59:38

Error setting up entry Securitas Sverige ***@me.com for alarmdotcom

```
Traceback (most recent call last):
  File "/config/custom_components/alarmdotcom/controller.py", line 107, in async_login
    login_result = await self._alarm.async_login()
  File "/usr/local/lib/python3.9/site-packages/pyalarmdotcomajax/__init__.py", line 188, in async_login
    await self._async_login_and_get_key()
  File "/usr/local/lib/python3.9/site-packages/pyalarmdotcomajax/__init__.py", line 943, in _async_login_and_get_key
    async with self._websession.get(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 535, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 542, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 907, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 986, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1081, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1111, in _create_connection_transport
    await waiter
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 335, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/alarmdotcom/__init__.py", line 39, in async_setup_entry
    if not await controller.async_setup():
  File "/config/custom_components/alarmdotcom/controller.py", line 141, in async_setup
    await self.async_login(
  File "/config/custom_components/alarmdotcom/controller.py", line 109, in async_login
    return login_result
  File "/usr/local/lib/python3.9/site-packages/async_timeout/__init__.py", line 129, in __aexit__
    self._do_exit(exc_type)
  File "/usr/local/lib/python3.9/site-packages/async_timeout/__init__.py", line 212, in _do_exit
    raise asyncio.TimeoutError
asyncio.exceptions.TimeoutError
```

Any ideas?

**Comment by Brkie** [comment] 2022-03-05 20:10
Just noticed that when I remove integration and add again, it works - until restart of server...

**Comment by HazardousRat** [comment] 2022-03-05 23:49
I'm experiencing the same issue however, upon integration I'm no longer receiving the 2FA code as I was previously.

**Comment by elahd** [comment] 2022-03-08 19:08
Would you mind running the integration for a few days with debugging enabled? This will provide more detailed logs next time you run into this problem. Add the following to configuration.yaml.

```yaml
logger:
  default: warn
  logs:
    custom_components.alarmdotcom: debug
    pyalarmdotcomajax: debug
```

When the error pops up again, check your Home Assistant logs for details.

Also, for now, instead of removing/re-adding the integration, try just reloading it:

![image](https://user-images.githubusercontent.com/466460/157307763-01c6f9f7-8dea-48dd-a0bb-7f355ebee7f7.png)

**Comment by rmatte** [comment] 2022-03-10 16:13
I was just coming here to report this.  I see the same thing.  Works fine until the home assistant server is restarted and then it fails to reconnect with the same message that the person who reported this included here.

**Comment by rmatte** [comment] 2022-03-23 20:32
Is it possible that the token that's established during the first login isn't getting saved or something?  I know with the older version of the plugin we had to login to the alarmdotcom interface and manually create a token string and then use that in the config.  That part seems to be automated now but maybe it's not working as expected after a restart of HA?

**Comment by elahd** [comment] 2022-03-26 16:15
You can check the cookie by digging into Home Assistant's config entry data store. If you're using Home Assistant OS, the easiest way to do this is by installing the "File Editor" add-in. (If you need a hand, there are good instructions on installing this add-in [here](https://www.home-assistant.io/getting-started/configuration/).)

Use the file editor to open `/config/.storage/core.config_entries`.  Search the file for `alarmdotcom`. (Don't use your browser's search function. Click into the text editor before pressing Ctrl+F in order to use file editor's own search function.) You should see an entry that looks like this (XXX indicates redaction):

```yaml
{
    "entry_id": "XXX",
    "version": 2,
    "domain": "alarmdotcom",
    "title": "XXX",
    "data": {
        "username": "XXX",
        "password": "XXX",
        "2fa_cookie": "XXX"
    },
    "options": {
        "arm_code": "XXX",
        "use_arm_code": true,
        "force_bypass": "Never",
        "no_entry_delay": "Never",
        "silent_arming": "Never"
    },
    "pref_disable_new_entities": false,
    "pref_disable_polling": false,
    "source": "user",
    "unique_id": "XXX",
    "disabled_by": null
}
```

`data.2fa_cookie` is the field of interest.

Just a warning to tread carefully here. This file isn't intended to be edited directly.

**Comment by elahd** [comment] 2022-04-03 20:50
@rmatte Would you mind testing v0.2.2-beta?

**Comment by rmatte** [comment] 2022-04-03 20:51
> @rmatte Would you mind testing v0.2.2-beta?

Sure thing, I'll do it right now.

**Comment by rmatte** [comment] 2022-04-03 21:28
> @rmatte Would you mind testing v0.2.2-beta?

I can confirm that changing the timeout in the code from 15 seconds to 30 has solved the problem.  I tested with both a restart of the ha core as well as a full reboot of the host.  Looks like we can close this one out.  Would be nice to get an updated version pushed to HACS.  I just hand patched the code on my host for now.

**Comment by rmatte** [comment] 2022-04-04 00:36
Actually, before we close this, it seems like sometimes when HA is reloaded or the host reboots I need to manually reconfigure the integration and log back in and provide another "one-time" code.  I want to see if this continues to be a trend or not.  If it does it's not going to be as nice as it was before where I never had to do this.  Maybe we need an option like before where we can just manually go in, create a key, and then specify it, instead of using the ones sent via text.

**Comment by elahd** [comment] 2022-04-04 16:14
If you are required to resubmit an OTP, I'd be curious to see whether there's a 2FA cookie in `/config/.storage/core.config_entries`.

I'm going to close this to keep the issues board tidy, but please do reopen if you continue running into this issue!

**Closed by elahd** 2022-04-04 16:14 UTC
