### ISSUE TITLE
Integration Intermittently Unavailable

### ISSUE THREAD

**Issue by mjmicks** [uvjustin/alarmdotcom#84] opened 2022-02-05 15:28 UTC
After restarting Home Assistant server, my Alarmdotcom integration intermittently will become ‘Unavailable’. After a couple more restarts, I can usually get it to become available again. 

**Log Details**

This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/alarmdotcom/controller.py:409 
Integration: Alarm.com (documentation, issues) 
First occurred: 10:22:37 AM (1 occurrences) 
Last logged: 10:22:37 AM

Error setting up entry [Alarmdotcom]: [email@email.com] for alarmdotcom

Traceback (most recent call last):
  File "/config/custom_components/alarmdotcom/controller.py", line 409, in get_controller
    await controller.async_login()
  File "/usr/local/lib/python3.9/site-packages/pyalarmdotcomajax/__init__.py", line 141, in async_login
    await self._async_login_and_get_key()
  File "/usr/local/lib/python3.9/site-packages/pyalarmdotcomajax/__init__.py", line 665, in _async_login_and_get_key
    async with self._websession.post(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 559, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 898, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
  File "/usr/local/lib/python3.9/site-packages/aiohttp/streams.py", line 616, in read
    await self._waiter
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 327, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/alarmdotcom/__init__.py", line 41, in async_setup_entry
    if not await controller.async_setup():
  File "/config/custom_components/alarmdotcom/controller.py", line 58, in async_setup
    self.api = await get_controller(
  File "/config/custom_components/alarmdotcom/controller.py", line 409, in get_controller
    await controller.async_login()
  File "/usr/local/lib/python3.9/site-packages/async_timeout/__init__.py", line 129, in __aexit__
    self._do_exit(exc_type)
  File "/usr/local/lib/python3.9/site-packages/async_timeout/__init__.py", line 212, in _do_exit
    raise asyncio.TimeoutError
asyncio.exceptions.TimeoutError

**Comment by elahd** [comment] 2022-02-08 18:34
Duplicate of #82

**Closed by elahd** 2022-02-08 18:34 UTC
