### ISSUE TITLE
Stuck on Loading Data

### ISSUE THREAD

**Issue by mjmicks** [uvjustin/alarmdotcom#69] opened 2022-01-23 06:25 UTC
Fresh install of Home Assistant OS on RPi 4. After setting up Alarmdotcom using these steps, homeassistant.local gets stuck in the Loading Data screen when attempting to login. So far, this has happened 2 times. First time I re-flashed SD card thinking it was a different integration causing the error. Setup as new, installed Alarmdotcom again through HACS custom components method, and everything gets added as expected. After adding all my sensors to their respective areas, and restarting home assistant server, that is when the Loading Data bug hits each time. This prevents me from accessing the UI, but Home Assistant is still running fine the entire time.

**Comment by elahd** [comment] 2022-01-23 15:33
Are you able to check your system logs for errors?

Configuration -> Settings -> Logs. If you see an error in the main card on that page for alarmdotcom, click on the error for the details and share that here. If you don't see an error in the card, hit the "Load Full Home Assistant Log" button, then search for "alarmdotcom".

Also, which provider are you using?

Thanks!

**Comment by elahd** [comment] 2022-01-24 01:29
Closing as duplicate of #70

**Comment by elahd** [comment] 2022-01-24 01:30
Duplicate of #70

**Closed by elahd** 2022-01-24 01:30 UTC

**Comment by mjmicks** [comment] 2022-01-24 04:16
I wish I would've saved the logs, but I've since removed the integration from my setup and no longer have access to them. The errors that stood out to me in the logs were related to my Garage Door (cover) control. My ADC account is through CPI Security.
